[tool.poetry]
name = "chainfactory-py"
version = "0.0.18b"
description = "Structured LLM Inference with Easy Parallelism and Tool Calling"
authors = ["Pankaj Garkoti <garkotipankaj@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "chainfactory"}]
include = ["chainfactory/chains/generate_prompt_template.fctr", "chainfactory/chains/generate_mask_template.fctr"]

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.1"
tiktoken = "^0.7.0"
cityhash = "^0.4.7"
pydantic-ai = "^0.1.0"
ipykernel = "^6.29.5"
colorama = "^0.4.6"
logfire = "^4.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
